--- 
Clone: 
  depth: 1
kind: pipeline
name: GengKapak
steps: 
  - name: Compile
    image: gengkapak/build:latest
    commands:
      - curl https://raw.githubusercontent.com/jsdclxvi/DroneCI/silont/run.sh | bash
    environment:
      TELEGRAM_TOKEN:
        from_secret: BOT_API_KEY
      GITHUB_TOKEN:
        from_secret: GH_TOKEN
    trigger: 
      branch: 
        - silont
